env:
  global:
    - CC_TEST_REPORTER_ID=31464536e34ab26588cb951d0fa6b5898abdf401dbe912fd47274df298e432ac

language: ruby

cache:
  bundler: true
  yarn: true
  directories:
     - /home/travis/.rvm/
rvm:
  - 2.7.1

services:
  - postgresql

addons:
  apt:
    - google-chrome-stable
    - chromium-chromedriver

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - psql -c 'create database casa_test;' -U postgres
  - ln -s /usr/lib/chromium-browser/chromedriver ~/bin/chromedriver

install:
  - travis_retry gem install bundler
  - travis_retry nvm install 13.7.0
  - travis_retry npm install --global yarn
  - travis_retry bundle install
  - travis_retry yarn
  - bundle install

script:
  - bundle exec rails webpacker:compile
  - bundle exec brakeman
  - RUBYOPT='-W:no-deprecated -W:no-experimental' bundle exec rspec

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT