# yamllint disable-line rule:document-start
blank_issues_enabled: false
contact_links:
  - name: ğŸ“„Documentation addition/change
    about: ğŸ”¨What needs documenting? âœ¨
    url: https://github.com/rubyforgood/casa/issues/new?template=documentation.md&projects=rubyforgood/casa/1
  - name: ğŸ§¹Chore
    about: ğŸ”¨What needs updating or removing? âœ¨
    url: https://github.com/rubyforgood/casa/issues/new?template=chore.md&projects=rubyforgood/casa/1
  - name: ğŸ™Problem Validation
    about: ğŸ”¨Describe a stakeholder's issueâœ¨
    url: https://github.com/rubyforgood/casa/issues/new?template=problem_validation.md&projects=rubyforgood/casa/1
