default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV.fetch("POSTGRES_USER") { } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  password: password

development:
  <<: *default
  database: casa_development
  host: <%= ENV.fetch("DATABASE_HOST") { } %>

test:
  <<: *default
  database: casa_test
  host: <%= ENV.fetch("DATABASE_HOST") { } %>

production:
  <<: *default
  database: casa_production
  username: casa
  password: <%= ENV['CASA_DATABASE_PASSWORD'] %>
