name: docker

on:
  push:
    branches:
      - main
    paths-ignore:
      - "doc/**"
      - "**/*.md"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "doc/**"
      - "**/*.md"

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create downloads folder
        run: |
          mkdir -p tmp/downloads
          chmod 777 tmp tmp/downloads
      - name: docker UP
        run: docker-compose up -d
      - name: db:reset
        run: docker-compose exec -T web rails db:reset
      - name: compile css
        run: docker-compose exec -T web bundle exec rails css:build
      - name: compile js
        run: docker-compose exec -T web bundle exec rails javascript:build
      - name: Test
        run: docker-compose exec -T web bundle exec rspec spec

      - name: Archive selenium screenshots
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: selenium-screenshots
          path: ${{ github.workspace }}/tmp/capybara/*.png
