name: docker

on:
  push:
    branches:
      - main
    paths-ignore:
      - "doc/**"
      - "**/*.md"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "doc/**"
      - "**/*.md"
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      RAILS_ENV: test
      TEST_MAX_DURATION: 60
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Create downloads folder
        run: |
          mkdir -p tmp/downloads
          chmod 777 tmp tmp/downloads
      - name: docker UP
        run: docker compose up -d
      - name: db:setup
        run: docker compose exec -T web rails db:setup
      - name: compile assets
        run: docker compose exec -T web bundle exec rails assets:precompile
      - name: Test
        run: docker compose exec -T web bundle exec rspec spec --fail-fast

      - name: Archive selenium screenshots
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: selenium-screenshots
          path: |
            ${{ github.workspace }}/tmp/capybara/*.png
            ${{ github.workspace }}/tmp/capybara/*.html
