name: ERB lint

on:
  push:
    branches:
      - main
    paths:
      - '**.erb'
  pull_request:
    branches:
      - main
    paths:
      - '**.erb'

jobs:
  erb_lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.4.0

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: ERB lint
      run: bundle exec erblint --lint-all
